services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    restart: on-failure
    develop:
      watch:
        - path: ./app
          target: /app
          action: sync
